---
- name: Software Deployment
  hosts: all
  become: true 
  vars_files: vars/main.yml

  tasks:

# Install packages 'apt-get install <name>'
    - name: Install packages
      apt_rpm:
        name: '{{ install_packages }}'
        state: present
        update_cache: yes

# Install packages 'epm play <name>'
    - name: Install packages EPM
      command: 
        cmd: epm play '{{ item }}'
      loop: 
        - draw.io
        - code
        - sublime

# Remove packages
    - name: Remove play
      apt_rpm:
        name: '{{ remove_play }}'
        state: absent